#' Test Xenium cell type spatial proximity enrichment via permutation
#'
#' Builds a spatial neighbor network independently within each stratum (for
#' example, sample or sample + ROI), counts observed cell-type-to-cell-type
#' edges, and compares those counts to a null distribution generated by
#' repeatedly permuting cell type labels while holding the network topology
#' fixed. This mirrors the permutation-based network test implemented by
#' Giotto's \code{cellProximityEnrichment()}: enrichment is expressed as a
#' z-score relative to the simulated null, and a permutation p-value is
#' computed for every unordered cell type pair (including same-type,
#' homotypic pairs).
#'
#' @param cds A monocle3 cell_data_set with Xenium centroid coordinates and
#'   cell type annotations in \code{colData(cds)}.
#' @param cell_type_col Column in \code{colData(cds)} containing cell type
#'   labels.
#' @param strata_cols Character vector of \code{colData(cds)} columns that
#'   define independent spatial networks. Networks are never built across
#'   strata. Defaults to \code{"sample"}.
#' @param roi_col Optional ROI column to append to \code{strata_cols}. This is
#'   a convenience for testing enrichment independently within ROIs created by
#'   \code{subset_xenium_rois()}; pass e.g. \code{roi_col = "roi_id"} to get
#'   per-sample-per-ROI statistics.
#' @param x_col,y_col Columns in \code{colData(cds)} containing centroid
#'   coordinates in microns.
#' @param network_method Spatial network used to define adjacency:
#'   \code{"delaunay"} (default, requires the \code{deldir} package) triangulates
#'   cell centroids, matching Giotto's default spatial network; \code{"knn"}
#'   connects each cell to its \code{k} nearest neighbors.
#' @param k Number of nearest neighbors per cell when
#'   \code{network_method = "knn"}. Ignored for \code{"delaunay"}.
#' @param max_distance Optional maximum centroid-to-centroid distance in
#'   microns. Network edges longer than this are dropped before counting,
#'   which trims long Delaunay edges at tissue borders. \code{NULL} keeps all
#'   edges.
#' @param n_permutations Number of label permutations used to build the null
#'   distribution for each stratum. Defaults to \code{1000}.
#' @param seed Random seed for reproducible permutations.
#' @param p_adjust_method Method passed to \code{stats::p.adjust()} for
#'   multiple testing correction, applied within each stratum. Defaults to
#'   \code{"BH"}.
#' @param sig_threshold Adjusted p-value threshold used to classify pairs as
#'   significantly enriched or depleted.
#' @param return_network Logical; if \code{TRUE}, include the per-stratum edge
#'   list used for testing.
#' @param return_simulations Logical; if \code{TRUE}, include the raw
#'   permutation count matrices for each stratum.
#' @param verbose Logical; print progress per stratum.
#'
#' @return An object of class \code{xenium_proximity_enrichment}, a list with:
#' \describe{
#'   \item{\code{enrichment}}{One row per stratum per unordered cell type pair
#'   (including same-type pairs), with observed edge count, mean and sd of the
#'   permuted null, a z-score enrichment statistic, permutation p-value,
#'   adjusted p-value, and an \code{interaction_type} classification of
#'   \code{"enriched"}, \code{"depleted"}, or \code{"not significant"}.}
#'   \item{\code{by_stratum}}{Cell type abundance and network node/edge counts
#'   for each stratum.}
#'   \item{\code{network}}{Per-stratum edge lists, returned when
#'   \code{return_network = TRUE}.}
#'   \item{\code{simulations}}{Per-stratum raw permutation count matrices,
#'   returned when \code{return_simulations = TRUE}.}
#' }
#'
#' @export
xenium_proximity_enrichment <- function(
    cds,
    cell_type_col = "cell_type",
    strata_cols = "sample",
    roi_col = NULL,
    x_col = "x_centroid",
    y_col = "y_centroid",
    network_method = c("delaunay", "knn"),
    k = 6,
    max_distance = NULL,
    n_permutations = 1000,
    seed = 1234,
    p_adjust_method = "BH",
    sig_threshold = 0.05,
    return_network = FALSE,
    return_simulations = FALSE,
    verbose = TRUE
) {
  network_method <- match.arg(network_method)
  if (network_method == "knn" && !requireNamespace("RANN", quietly = TRUE)) {
    stop("Package 'RANN' is required for network_method = \"knn\".")
  }
  if (network_method == "delaunay" && !requireNamespace("deldir", quietly = TRUE)) {
    stop("Package 'deldir' is required for network_method = \"delaunay\". ",
      "Install it or use network_method = \"knn\".")
  }
  validate_xenium_enrichment_args(
    cell_type_col = cell_type_col,
    strata_cols = strata_cols,
    roi_col = roi_col,
    x_col = x_col,
    y_col = y_col,
    k = k,
    max_distance = max_distance,
    n_permutations = n_permutations,
    sig_threshold = sig_threshold
  )

  if (!is.null(roi_col)) {
    strata_cols <- unique(c(strata_cols, roi_col))
  }

  cd <- as.data.frame(SummarizedExperiment::colData(cds))
  required_cols <- unique(c(cell_type_col, strata_cols, x_col, y_col))
  missing_cols <- setdiff(required_cols, colnames(cd))
  if (length(missing_cols) > 0) {
    stop("Required columns missing from colData(cds): ", paste(missing_cols, collapse = ", "))
  }

  cd$cell_id <- rownames(cd)
  cd$.cell_type <- as.character(cd[[cell_type_col]])
  cd$.x <- as.numeric(cd[[x_col]])
  cd$.y <- as.numeric(cd[[y_col]])
  cd$.stratum <- make_xenium_proximity_stratum(cd, strata_cols)
  cd$stratum <- cd$.stratum

  keep <- !is.na(cd$.cell_type) & nzchar(cd$.cell_type) &
    !is.na(cd$.stratum) & nzchar(cd$.stratum) &
    is.finite(cd$.x) & is.finite(cd$.y)
  dropped <- sum(!keep)
  if (dropped > 0) {
    warning(dropped, " cells with missing cell type, stratum, or coordinates were ignored.")
  }
  cd <- cd[keep, , drop = FALSE]
  if (nrow(cd) < 3) {
    stop("At least three cells with complete metadata are required.")
  }

  split_cd <- split(cd, cd$.stratum)
  set.seed(seed)
  stratum_results <- lapply(names(split_cd), function(stratum_name) {
    if (verbose) {
      message("Testing proximity enrichment for stratum: ", stratum_name)
    }
    test_xenium_stratum_enrichment(
      sample_cd = split_cd[[stratum_name]],
      strata_cols = strata_cols,
      network_method = network_method,
      k = as.integer(k),
      max_distance = max_distance,
      n_permutations = as.integer(n_permutations)
    )
  })
  names(stratum_results) <- names(split_cd)

  enrichment <- dplyr::bind_rows(lapply(stratum_results, `[[`, "enrichment"))
  if (nrow(enrichment) == 0) {
    stop("No spatial network edges were retained in any stratum. ",
      "Check coordinates, k, or max_distance.")
  }
  enrichment <- enrichment |>
    dplyr::group_by(dplyr::across(dplyr::all_of(strata_cols))) |>
    dplyr::mutate(p_adj = stats::p.adjust(p_value, method = p_adjust_method)) |>
    dplyr::ungroup() |>
    dplyr::mutate(
      interaction_type = dplyr::case_when(
        p_adj < sig_threshold & enrichment > 0 ~ "enriched",
        p_adj < sig_threshold & enrichment < 0 ~ "depleted",
        TRUE ~ "not significant"
      )
    ) |>
    dplyr::arrange(dplyr::across(dplyr::all_of(c(strata_cols, "cell_type_a", "cell_type_b"))))

  by_stratum <- dplyr::bind_rows(lapply(stratum_results, `[[`, "by_stratum"))

  result <- list(enrichment = enrichment, by_stratum = by_stratum)
  if (return_network) {
    result$network <- lapply(stratum_results, `[[`, "network")
  }
  if (return_simulations) {
    result$simulations <- lapply(stratum_results, `[[`, "simulations")
  }
  attr(result, "strata_cols") <- strata_cols
  attr(result, "params") <- list(
    network_method = network_method,
    k = k,
    max_distance = max_distance,
    n_permutations = n_permutations,
    seed = seed,
    p_adjust_method = p_adjust_method,
    sig_threshold = sig_threshold
  )
  class(result) <- c("xenium_proximity_enrichment", class(result))
  result
}

validate_xenium_enrichment_args <- function(cell_type_col, strata_cols, roi_col, x_col, y_col,
                                             k, max_distance, n_permutations, sig_threshold) {
  if (!is.character(cell_type_col) || length(cell_type_col) != 1) {
    stop("cell_type_col must be a single column name.")
  }
  if (!is.character(strata_cols) || length(strata_cols) < 1 || anyNA(strata_cols)) {
    stop("strata_cols must be a non-empty character vector.")
  }
  if (!is.null(roi_col) && (!is.character(roi_col) || length(roi_col) != 1)) {
    stop("roi_col must be NULL or a single column name.")
  }
  if (!is.character(x_col) || length(x_col) != 1 || !is.character(y_col) || length(y_col) != 1) {
    stop("x_col and y_col must each be a single column name.")
  }
  if (!is.numeric(k) || length(k) != 1 || is.na(k) || k < 1) {
    stop("k must be a positive integer.")
  }
  if (!is.null(max_distance) &&
      (!is.numeric(max_distance) || length(max_distance) != 1 || is.na(max_distance) || max_distance <= 0)) {
    stop("max_distance must be NULL or a positive number.")
  }
  if (!is.numeric(n_permutations) || length(n_permutations) != 1 || is.na(n_permutations) || n_permutations < 1) {
    stop("n_permutations must be a positive integer.")
  }
  if (!is.numeric(sig_threshold) || length(sig_threshold) != 1 || is.na(sig_threshold) ||
      sig_threshold <= 0 || sig_threshold >= 1) {
    stop("sig_threshold must be a number between 0 and 1.")
  }
}

build_xenium_delaunay_edges <- function(xy) {
  d <- deldir::deldir(xy[, 1], xy[, 2])
  edges <- as.matrix(d$delsgs[, c("ind1", "ind2")])
  storage.mode(edges) <- "integer"
  colnames(edges) <- c("from", "to")
  edges
}

build_xenium_knn_edges <- function(xy, k) {
  n <- nrow(xy)
  k_search <- min(n, k + 1L)
  nn <- RANN::nn2(data = xy, query = xy, k = k_search, searchtype = "standard")
  from <- rep(seq_len(n), each = k_search)
  to <- as.vector(t(nn$nn.idx))
  keep <- from != to
  cbind(from = from[keep], to = to[keep])
}

build_xenium_proximity_network <- function(sample_cd, network_method, k, max_distance) {
  n <- nrow(sample_cd)
  xy <- as.matrix(sample_cd[, c(".x", ".y")])
  edges <- if (network_method == "delaunay") {
    build_xenium_delaunay_edges(xy)
  } else {
    build_xenium_knn_edges(xy, k)
  }
  if (nrow(edges) == 0) {
    return(data.frame(from = integer(0), to = integer(0), distance = numeric(0)))
  }

  lo <- pmin(edges[, "from"], edges[, "to"])
  hi <- pmax(edges[, "from"], edges[, "to"])
  not_self <- lo != hi
  lo <- lo[not_self]
  hi <- hi[not_self]
  keep_unique <- !duplicated(paste(lo, hi, sep = "_"))
  from <- lo[keep_unique]
  to <- hi[keep_unique]

  distance <- sqrt((xy[from, 1] - xy[to, 1])^2 + (xy[from, 2] - xy[to, 2])^2)
  if (!is.null(max_distance)) {
    keep <- distance <= max_distance
    from <- from[keep]
    to <- to[keep]
    distance <- distance[keep]
  }
  data.frame(from = from, to = to, distance = distance)
}

pair_combo_lookup <- function(n_types) {
  combo_matrix <- matrix(NA_integer_, n_types, n_types)
  upper <- upper.tri(combo_matrix, diag = TRUE)
  combo_matrix[upper] <- seq_len(sum(upper))
  combo_matrix[lower.tri(combo_matrix)] <- t(combo_matrix)[lower.tri(combo_matrix)]
  positions <- which(upper, arr.ind = TRUE)
  list(
    matrix = combo_matrix,
    type_a_idx = positions[, "row"],
    type_b_idx = positions[, "col"],
    n_combos = sum(upper)
  )
}

count_pair_combos <- function(type_code, from_idx, to_idx, combo_lookup) {
  pair_ids <- combo_lookup$matrix[cbind(type_code[from_idx], type_code[to_idx])]
  tabulate(pair_ids, nbins = combo_lookup$n_combos)
}

test_xenium_stratum_enrichment <- function(sample_cd, strata_cols, network_method, k,
                                            max_distance, n_permutations) {
  n <- nrow(sample_cd)
  edges <- build_xenium_proximity_network(sample_cd, network_method, k, max_distance)

  types <- sort(unique(sample_cd$.cell_type))
  n_types <- length(types)
  type_code <- match(sample_cd$.cell_type, types)
  combo_lookup <- pair_combo_lookup(n_types)

  abundance <- as.data.frame(table(cell_type = sample_cd$.cell_type), stringsAsFactors = FALSE)
  names(abundance) <- c("cell_type", "n_cells")
  strata_row <- sample_cd[1, strata_cols, drop = FALSE]
  by_stratum <- data.frame(
    strata_row[rep(1, nrow(abundance)), , drop = FALSE],
    stratum = sample_cd$.stratum[1],
    abundance,
    stratum_total_cells = n,
    network_nodes = n,
    network_edges = nrow(edges),
    row.names = NULL
  )

  if (nrow(edges) == 0) {
    return(list(
      enrichment = data.frame(),
      by_stratum = by_stratum,
      network = data.frame(
        cell_id_a = character(0), cell_type_a = character(0),
        cell_id_b = character(0), cell_type_b = character(0),
        distance = numeric(0)
      ),
      simulations = NULL
    ))
  }

  from_idx <- edges$from
  to_idx <- edges$to
  observed <- count_pair_combos(type_code, from_idx, to_idx, combo_lookup)

  sim_counts <- matrix(NA_real_, nrow = n_permutations, ncol = combo_lookup$n_combos)
  for (i in seq_len(n_permutations)) {
    permuted_code <- sample(type_code)
    sim_counts[i, ] <- count_pair_combos(permuted_code, from_idx, to_idx, combo_lookup)
  }

  mean_sim <- colMeans(sim_counts)
  sd_sim <- apply(sim_counts, 2, stats::sd)
  z_score <- ifelse(sd_sim > 0, (observed - mean_sim) / sd_sim, 0)

  p_gt <- (colSums(sweep(sim_counts, 2, observed, `>=`)) + 1) / (n_permutations + 1)
  p_lt <- (colSums(sweep(sim_counts, 2, observed, `<=`)) + 1) / (n_permutations + 1)
  p_value <- pmin(1, 2 * pmin(p_gt, p_lt))

  enrichment <- data.frame(
    sample_cd[rep(1, combo_lookup$n_combos), strata_cols, drop = FALSE],
    stratum = sample_cd$.stratum[1],
    cell_type_a = types[combo_lookup$type_a_idx],
    cell_type_b = types[combo_lookup$type_b_idx],
    observed = observed,
    expected = mean_sim,
    sd_sim = sd_sim,
    enrichment = z_score,
    p_value = p_value,
    row.names = NULL
  )

  network_table <- data.frame(
    sample_cd[from_idx, strata_cols, drop = FALSE],
    stratum = sample_cd$.stratum[1],
    cell_id_a = sample_cd$cell_id[from_idx],
    cell_type_a = sample_cd$.cell_type[from_idx],
    cell_id_b = sample_cd$cell_id[to_idx],
    cell_type_b = sample_cd$.cell_type[to_idx],
    distance = edges$distance,
    row.names = NULL
  )

  list(
    enrichment = enrichment,
    by_stratum = by_stratum,
    network = network_table,
    simulations = sim_counts
  )
}

#' Plot a heatmap of Xenium cell type proximity enrichment
#'
#' @param enrichment_result Object returned by \code{xenium_proximity_enrichment()}.
#' @param value Statistic to fill tiles with. Defaults to \code{"enrichment"}
#'   (the permutation z-score).
#' @param facet Logical; if \code{TRUE}, facet the heatmap by stratum.
#' @param show_significance Logical; if \code{TRUE}, mark tiles with
#'   \code{p_adj} below the enrichment's significance threshold with an
#'   asterisk.
#'
#' @return A ggplot heatmap.
#'
#' @export
plot_xenium_proximity_heatmap <- function(
    enrichment_result,
    value = c("enrichment", "p_adj", "observed"),
    facet = TRUE,
    show_significance = TRUE
) {
  check_xenium_enrichment_result(enrichment_result)
  value <- match.arg(value)
  enrichment <- enrichment_result$enrichment
  sig_threshold <- attr(enrichment_result, "params")$sig_threshold %||% 0.05

  plot_data <- dplyr::bind_rows(
    enrichment,
    dplyr::rename(enrichment, cell_type_a = cell_type_b, cell_type_b = cell_type_a)
  ) |>
    dplyr::distinct()

  p <- ggplot2::ggplot(
    plot_data,
    ggplot2::aes_string(x = "cell_type_b", y = "cell_type_a", fill = value)
  ) +
    ggplot2::geom_tile() +
    ggplot2::labs(x = "Cell type", y = "Cell type", fill = value) +
    ggplot2::theme_minimal() +
    ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 45, hjust = 1))

  if (value == "enrichment") {
    p <- p + ggplot2::scale_fill_gradient2(low = "#2166AC", mid = "white", high = "#B2182B")
  }
  if (show_significance) {
    plot_data$.sig_label <- ifelse(plot_data$p_adj < sig_threshold, "*", "")
    p <- p + ggplot2::geom_text(
      data = plot_data,
      ggplot2::aes_string(x = "cell_type_b", y = "cell_type_a", label = ".sig_label"),
      inherit.aes = FALSE, vjust = 0.75
    )
  }
  if (facet && "stratum" %in% colnames(plot_data)) {
    p <- p + ggplot2::facet_wrap(stats::as.formula("~ stratum"))
  }
  p
}

#' Plot a barplot of the top Xenium cell type proximity interactions
#'
#' Mirrors Giotto's \code{cellProximityBarplot()}: shows the interactions with
#' the strongest evidence of enrichment or depletion, ranked by absolute
#' enrichment z-score.
#'
#' @param enrichment_result Object returned by \code{xenium_proximity_enrichment()}.
#' @param top_n Number of top interactions to show per stratum.
#' @param significant_only Logical; if \code{TRUE}, only pairs classified as
#'   \code{"enriched"} or \code{"depleted"} are eligible to be shown.
#' @param facet Logical; if \code{TRUE}, facet the barplot by stratum.
#'
#' @return A ggplot barplot.
#'
#' @export
plot_xenium_proximity_barplot <- function(
    enrichment_result,
    top_n = 20,
    significant_only = TRUE,
    facet = TRUE
) {
  check_xenium_enrichment_result(enrichment_result)
  enrichment <- enrichment_result$enrichment
  if (significant_only) {
    enrichment <- enrichment[enrichment$interaction_type != "not significant", , drop = FALSE]
  }
  if (nrow(enrichment) == 0) {
    stop("No interactions available to plot. Set significant_only = FALSE or relax sig_threshold.")
  }

  enrichment$pair_label <- paste(enrichment$cell_type_a, enrichment$cell_type_b, sep = " -- ")
  group_col <- if ("stratum" %in% colnames(enrichment)) "stratum" else NULL

  top_rows <- if (is.null(group_col)) {
    enrichment[order(-abs(enrichment$enrichment)), , drop = FALSE][seq_len(min(top_n, nrow(enrichment))), ]
  } else {
    dplyr::bind_rows(lapply(split(enrichment, enrichment[[group_col]]), function(df) {
      df[order(-abs(df$enrichment)), , drop = FALSE][seq_len(min(top_n, nrow(df))), ]
    }))
  }
  top_rows$pair_label <- factor(top_rows$pair_label, levels = unique(top_rows$pair_label[order(top_rows$enrichment)]))

  p <- ggplot2::ggplot(
    top_rows,
    ggplot2::aes_string(x = "pair_label", y = "enrichment", fill = "interaction_type")
  ) +
    ggplot2::geom_col() +
    ggplot2::coord_flip() +
    ggplot2::scale_fill_manual(values = c(
      "enriched" = "#B2182B", "depleted" = "#2166AC", "not significant" = "grey70"
    )) +
    ggplot2::labs(x = NULL, y = "Enrichment (z-score)", fill = "Interaction") +
    ggplot2::theme_minimal()

  if (facet && !is.null(group_col)) {
    p <- p + ggplot2::facet_wrap(stats::as.formula(paste0("~ ", group_col)), scales = "free_y")
  }
  p
}

#' Plot a network diagram of Xenium cell type proximity interactions
#'
#' Draws cell types as nodes on a circular layout, shared across strata for
#' visual comparability, and connects significantly enriched or depleted
#' cell-type pairs with edges colored by interaction direction and weighted
#' by enrichment magnitude. Homotypic (same-type) interactions are shown as a
#' colored ring around the corresponding node.
#'
#' @param enrichment_result Object returned by \code{xenium_proximity_enrichment()}.
#' @param stratum Optional single stratum value to plot. If \code{NULL} and
#'   multiple strata are present, the plot is faceted by stratum.
#' @param significant_only Logical; if \code{TRUE}, only pairs classified as
#'   \code{"enriched"} or \code{"depleted"} are drawn as edges.
#'
#' @return A ggplot network diagram.
#'
#' @export
plot_xenium_proximity_network <- function(
    enrichment_result,
    stratum = NULL,
    significant_only = TRUE
) {
  check_xenium_enrichment_result(enrichment_result)
  enrichment <- enrichment_result$enrichment
  if (!is.null(stratum)) {
    enrichment <- enrichment[enrichment$stratum == stratum, , drop = FALSE]
    if (nrow(enrichment) == 0) {
      stop("stratum not found in enrichment_result: ", stratum)
    }
  }

  types <- sort(unique(c(enrichment$cell_type_a, enrichment$cell_type_b)))
  n_types <- length(types)
  angles <- seq(0, 2 * pi, length.out = n_types + 1)[seq_len(n_types)]
  layout <- data.frame(
    cell_type = types,
    x = cos(angles),
    y = sin(angles),
    stringsAsFactors = FALSE
  )

  edges <- enrichment[enrichment$cell_type_a != enrichment$cell_type_b, , drop = FALSE]
  if (significant_only) {
    edges <- edges[edges$interaction_type != "not significant", , drop = FALSE]
  }
  edges <- merge(edges, layout, by.x = "cell_type_a", by.y = "cell_type")
  edges <- merge(edges, layout, by.x = "cell_type_b", by.y = "cell_type", suffixes = c("_a", "_b"))

  nodes <- enrichment[enrichment$cell_type_a == enrichment$cell_type_b, , drop = FALSE]
  nodes <- merge(layout, nodes[, c("cell_type_a", "enrichment", "interaction_type", "stratum")],
    by.x = "cell_type", by.y = "cell_type_a", all.x = TRUE)

  p <- ggplot2::ggplot()
  if (nrow(edges) > 0) {
    p <- p + ggplot2::geom_segment(
      data = edges,
      ggplot2::aes_string(
        x = "x_a", y = "y_a", xend = "x_b", yend = "y_b",
        color = "interaction_type", size = "abs(enrichment)"
      ),
      alpha = 0.7
    )
  }
  p <- p +
    ggplot2::geom_point(
      data = nodes,
      ggplot2::aes_string(x = "x", y = "y", fill = "interaction_type"),
      shape = 21, size = 8, stroke = 1.2
    ) +
    ggplot2::geom_text(
      data = layout,
      ggplot2::aes_string(x = "x * 1.15", y = "y * 1.15", label = "cell_type")
    ) +
    ggplot2::scale_color_manual(values = c(
      "enriched" = "#B2182B", "depleted" = "#2166AC", "not significant" = "grey70"
    )) +
    ggplot2::scale_fill_manual(values = c(
      "enriched" = "#B2182B", "depleted" = "#2166AC", "not significant" = "white"
    ), na.value = "white") +
    ggplot2::coord_fixed(clip = "off") +
    ggplot2::theme_void() +
    ggplot2::labs(color = "Interaction", fill = "Homotypic", size = "|enrichment|")

  if (is.null(stratum) && "stratum" %in% colnames(enrichment) && dplyr::n_distinct(enrichment$stratum) > 1) {
    p <- p + ggplot2::facet_wrap(stats::as.formula("~ stratum"))
  }
  p
}

check_xenium_enrichment_result <- function(enrichment_result) {
  if (!inherits(enrichment_result, "xenium_proximity_enrichment") || is.null(enrichment_result$enrichment)) {
    stop("enrichment_result must be an object returned by xenium_proximity_enrichment().")
  }
}

`%||%` <- function(x, y) if (is.null(x)) y else x

if (getRversion() >= "2.15.1") {
  utils::globalVariables(c(
    "cell_type_a",
    "cell_type_b",
    "p_value",
    "p_adj",
    "interaction_type"
  ))
}
